# Generated by Django 2.2.6 on 2019-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20191209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='shoes/no-disponible.png', upload_to='shoes'),
        ),
    ]
