# Generated by Django 2.2.6 on 2019-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191209_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
